#!/bin/bash

ROW0=/sys/bus/i2c/devices/1-003c/writechar_row0
ROW1=/sys/bus/i2c/devices/1-003c/writechar_row1
ROW7=/sys/bus/i2c/devices/1-003c/writechar_row7
ROW3TO6_LARGE=/sys/bus/i2c/devices/1-003c/rows2to6_large5

clrscr()
{
echo '' > ${ROW0}
echo '' > ${ROW1}
echo '' > ${ROW7}
}


#--- 'main'
KDRV=ssd1306
[[ "$1" = "-b" ]] && {
  echo "lkm ${KDRV}"
  lkm ${KDRV}
}

lsmod |grep -w ${KDRV} >/dev/null 2>&1 || {
  if [[ -f ${KDRV}.ko ]] ; then
     sudo insmod ./${KDRV}.ko
  else
     lkm ${KDRV}
  fi
}

sudo chmod 0222 ${ROW0} ${ROW1} ${ROW7} ${ROW3TO6_LARGE} || exit 1

clrscr

#echo 'degrees Celsius' > ${ROW1}
echo 'Env Info Prj' > ${ROW7}

#echo -n "99.9C" > ${ROW3TO6_LARGE}
#echo -n "24.8C" > ${ROW3TO6_LARGE}

#echo 'HUMIDITY' > ${ROW0}
#echo -n "74.8%" > ${ROW3TO6_LARGE}
#exit 0


for i in $(seq 0 9) ; do
	#echo -n "7.${i}H" > ${ROW3TO6_LARGE}
	echo 'TEMPERATURE' > ${ROW0}
	echo -n "28.${i}C" > ${ROW3TO6_LARGE}
	sleep 2
	echo 'HUMIDITY %' > ${ROW0}
	echo -n "88.${i}%" > ${ROW3TO6_LARGE}
	sleep 2
done

dmesg
