#!/bin/sh
[ $(id -u) -ne 0 ] && {
	echo "needs root."
	exit 1
}
SYSFS_ENTRY=/sys/bus/i2c/devices/1-003c/writechar

[ 0 -eq 1 ] && {
for i in $(seq 0 9)
do
	echo $i > ${SYSFS_ENTRY}
	sleep .5
done
}

data1="01234567890123456789"
data="${data1} ${data1} ${data1} ${data1} ${data1} ${data1} ${data1} ${data1}"
echo "${data}" > ${SYSFS_ENTRY}
