#!/bin/bash
# Wrapper over our simple ledblink_bbb.sh script
# NOTE: meant for the TI BeagleBone Black / BeaglePlay boards
# running standard Debian

[ $# -ne 1 ] && {
	echo "Usage: $0 1 (right-to-left)
       $0 2 (left-to-right)
	"
	exit 1
}

trap './turn_off_all_userleds; exit 0' INT QUIT EXIT

if [ $1 -eq 1 ]; then
  while [[ true ]] ; do
    sudo ./ledblink_bbb.sh 0
    sudo ./ledblink_bbb.sh 1
    sudo ./ledblink_bbb.sh 2
    sudo ./ledblink_bbb.sh 3
  done
elif [ $1 -eq 2 ]; then
  while [[ true ]] ; do
    sudo ./ledblink_bbb.sh 3
    sudo ./ledblink_bbb.sh 2
    sudo ./ledblink_bbb.sh 1
    sudo ./ledblink_bbb.sh 0
  done
fi
