#!/bin/bash
# To be invoked from parent folder via the Makefile.bbb
DTS=bbb_dts/bbb_i2c2_dht2x.dts
DTBO=bbb_dts/BBB-I2C2-DHT2X.dtbo
UBOOT_LOC=/boot/dtbs/$(uname -r)/overlays

dtc -I dts -O dtb -@ ${DTS} -o ${DTBO} || {
  echo "FAILED to generate the DTBO" ; exit 1
}

sudo cp ${DTBO} ${UBOOT_LOC}/
ls -l ${UBOOT_LOC}/$(basename ${DTBO})

echo "Verifying it's in the /boot/uEnv.txt..."
grep "^dtb_overlay.*=${UBOOT_LOC}/$(basename ${DTBO})" /boot/uEnv.txt || {
  echo "
FAILED to verify presence of our DTBO; please add this line to /boot/uEnv.txt and then retry:
dtb_overlay=${UBOOT_LOC}/$(basename ${DTBO})
-OR- add it to one of the dtb_boot_addr4 to addr7 lines, f.e.
dtb_overlay_addr4=${UBOOT_LOC}/$(basename ${DTBO})"
  exit 1
}
echo "OK, verified; if DTS modified, reboot and then test, else you can run the kernel driver now..."
exit 0
