#!/bin/bash

DTS=bbb_dht2x.dts
DTBO=BBB-DHT2X.dtbo
UBOOT_LOC=/boot/dtbs/5.10.168-ti-r71/overlays

dtc -I dts -O dtb -@ ${DTS} -o ${DTBO} || {
  echo "FAILED to generate the DTBO" ; exit 1
}

sudo cp ${DTBO} ${UBOOT_LOC}/
ls -l ${UBOOT_LOC}/${DTBO}

echo "Verifying it's in the /boot/uEnv.txt..."
grep "^dtb_overlay=${UBOOT_LOC}/${DTBO}" /boot/uEnv.txt || {
  echo "
FAILED to verify presence of our DTBO; please add this line to /boot/uEnv.txt and then retry:
dtb_overlay=${UBOOT_LOC}/${DTBO}
" ; exit 1
}
echo "OK, verified; if DTS modified, reboot and then test, else you can run the kernel driver now..."
exit 0
